
spring.datasource.url=jdbc:postgresql://dpg-d8j1tgflk1mc738nrl4g-a.oregon-postgres.render.com:5432/incentivos_ygr8
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=incentivosdb_tfw4_user
spring.datasource.password=bJSEz81VSXvvEj4WTBe7utCiXBBq8owY
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

DONADORES_Y_ENTIDADES=https://donadoresyentidades.onrender.com
DONACIONES_SERVICE_URL=


# --- Datadog / Micrometer (Spring Boot 3.x usa el prefijo management.datadog.metrics.export.*) ---
management.datadog.metrics.export.api-key=900a4364fe88ed3ba1d5a131ba792a67
management.datadog.metrics.export.step=1m
management.datadog.metrics.export.uri=https://api.datadoghq.com
management.metrics.tags.modulo=Incentivos
management.datadog.metrics.export.applicationKey=ddapp_ru3axwXfAfAjqut8T8XFq71eWlKz4BtpTk
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

 
spring.devtools.restart.enabled=true


server.port=${PORT:8080}